Added nested Widget creation and modification example
UmbraLuminosa/sickle_ui pull request #117
Opened 2024-09-27 22:04 UTC by TotalKrill

Created an example of creating custom widgets, and examples of modifications of those widgets with widgetlike trees

Didnt figure out any nicer way of getting the Component that is required for the typed 'UiBuilder<'_, (Entity, Component)>'
and also it was so tedious to create the extension traits when trying to get a reference to the component.

And I still included the extension trait crate as dev-dep, to showcase an even easier use that is optional for users of this great library!

2024-09-27 22:54 UTC, eidloi requested changes
I can see how this is useful, thanks for putting it together!

2024-09-27 22:54 UTC, eidloi commented on examples/widget.rs
> +impl EntityCommand for SetText {
this already exists in the scaffold: https://github.com/UmbraLuminosa/sickle_ui/blob/5b4d0df655087dd140a43c0bad7bc48b1fd9d8a2/crates/sickle_ui_scaffold/src/ui_commands.rs#L102

(set text needs a text style, but update text doesn't)

2024-09-27 22:54 UTC, eidloi commented on examples/widget.rs
> +        let tl = title_labels.get(entity).unwrap();
Normally the place of invocation should take care of grabbing the `UiBuilder` below (like, in a system where you use it from). But to support pure command approach you can wrap this entire thing in a command so you don't need the component query:
```rust
 self.entity_commands().add(|entity, world: &mut World| {
    // NOTE: Component needs to be `Clone`
    let Some(context) = world.get::<TitledLabel>(entity).cloned() else {
        return;
    };
    let mut commands = world.commands();
    let mut builder = commands.ui_builder((entity, context));
    // spawn_children: impl FnOnce(&mut UiBuilder<(Entity, TabContainer)>) + Send + Sync + 'static,
    spawn_children(&mut builder);
});
```

2024-09-27 22:54 UTC, eidloi commented on examples/widget.rs
> +        let tl = title_labels.get(entity).unwrap();
BTW the purpose of this is to hide complexity and to manage the deferred nature of the commands chain. You could move the closure to a proper EntityCommand that would accept the regular fn, wrapped properly in an Arc. There are examples of this around for instance where we allow custom style commands: 
https://github.com/UmbraLuminosa/sickle_ui/blob/5b4d0df655087dd140a43c0bad7bc48b1fd9d8a2/crates/sickle_ui_scaffold/src/ui_style/builder.rs#L18
And the storage struct: https://github.com/UmbraLuminosa/sickle_ui/blob/5b4d0df655087dd140a43c0bad7bc48b1fd9d8a2/crates/sickle_ui_scaffold/src/ui_style/attribute.rs#L178

This is not necessary for this PR, but a comment pointing it out would be nice to have.

2024-09-27 22:54 UTC, eidloi commented on examples/widget.rs
> +            title: "Sickle UI -  Simple Editor".into(),
you can name the example here

2024-09-28 15:56 UTC, TotalKrill commented on examples/widget.rs
> +        let tl = title_labels.get(entity).unwrap();
Hmm, I am having a hard time wrapping my head around this

But what I was trying to achieve is a more "ZeroKnowledge" usage. Meaning, that I am aiming for a DevX that enables the LSP to solve discoveribility, while also reducing the possibility of failures. 

Trying to modify the closure to command, gives me errors such as "Is not thread safe", which would require me to set the lifetime to static, as in your linked example. 

I think the code found a good balance when requiring the Query, it became more clear where the data was accessed from, so I think that I will keep it that way.  And using the closure I managed to use references, which made the code less "cloney" :)

The final thing I would like to improve is when storing of the Entities on the Components, I would like to get some type hints there, but keeping them private is acceptable to me, that way I embedd the type hints and access code in the methods. 

I am fairly happy with this example now

2024-09-28 16:06 UTC, eidloi commented on examples/widget.rs
> +        let tl = title_labels.get(entity).unwrap();
> Trying to modify the closure to command, gives me errors such as "Is not thread safe", which would require me to set the lifetime to static, as in your linked example.
> 

see the comment in the code, you need `+ Send + Sync + 'static,` on the builder argument. But yeah it's more of a preference on how far you go with the prepared methods vs. how much you expect from external devs. Using references is also a use case, so good enough for me!

2024-09-28 16:39 UTC, TotalKrill commented on examples/widget.rs
> +impl EntityCommand for SetText {
yeah I removed the custom implementation, I dont think this example needs to showcase that. 

Rather have another smaller example just for that...

2024-09-28 16:40 UTC, TotalKrill commented
Please have a look to see if i missed something obvious again. 

my goal here is to get someone wanting to create widgets for sickle_ui a starting ground and suggested path :)

2024-09-28 16:53 UTC, eidloi reviewed
These are just nits, I am not gonna hold back the PR for them if you want to go ahead! However, do you see the button below to rebase on main? Not sure what happens when _I_ click it since the source branch is in your repo....

2024-09-28 16:53 UTC, eidloi commented on crates/sickle_ui_scaffold/src/ui_builder.rs
> +    fn get_id(&self) -> Entity {
this can be called simply `id`, to be in line with the other traits

2024-09-28 16:53 UTC, eidloi commented on crates/sickle_ui_scaffold/src/ui_builder.rs
> +    pub fn style_inplace(&mut self, style_fn: impl FnOnce(&mut UiStyle)) -> &mut Self {
this is a great idea!

2024-09-28 16:53 UTC, eidloi commented on crates/sickle_ui_scaffold/src/ui_builder.rs
> +    pub fn content(&self) -> &T {
the name `content` could be confusing during usage as it _might_ seem it is the content of the widget frame. Maybe `component` or `context_data`?

2024-09-28 16:53 UTC, eidloi commented on crates/sickle_ui_scaffold/src/ui_builder.rs
> +impl UiBuilderExt for EntityCommands<'_> {
oh, this works now? I had to give up on it due to lifetime issue with the commands.

2024-09-28 16:53 UTC, eidloi approved these changes

2024-09-28 16:53 UTC, eidloi commented
ah never mind, merging is possible as-is

2024-09-28 16:54 UTC, TotalKrill commented on crates/sickle_ui_scaffold/src/ui_builder.rs
> +    fn get_id(&self) -> Entity {
The trait, or the method, I didnt want to start including the trait everywhere across the codebase. thats why the trait has get_id and the id() on UiBuilder is still the same

2024-09-28 16:55 UTC, TotalKrill commented on crates/sickle_ui_scaffold/src/ui_builder.rs
> +    pub fn content(&self) -> &T {
context_data is better i believe :)

2024-09-28 16:57 UTC, eidloi commented on crates/sickle_ui_scaffold/src/ui_builder.rs
> +    fn get_id(&self) -> Entity {
I'll sync that in a follow up, no worries.

2024-09-28 16:57 UTC, TotalKrill commented on crates/sickle_ui_scaffold/src/ui_builder.rs
> +    pub fn style_inplace(&mut self, style_fn: impl FnOnce(&mut UiStyle)) -> &mut Self {
should I add an entity_commands_inplace as well?

2024-09-28 16:58 UTC, TotalKrill commented on crates/sickle_ui_scaffold/src/ui_builder.rs
> +impl UiBuilderExt for EntityCommands<'_> {
Seems like it :) no issues for me on both stable and nightly

2024-09-28 17:00 UTC, eidloi commented on crates/sickle_ui_scaffold/src/ui_builder.rs
> +    pub fn style_inplace(&mut self, style_fn: impl FnOnce(&mut UiStyle)) -> &mut Self {
I won't stop you :D

2024-09-28 17:13 UTC, TotalKrill commented
I feel done now :) thanks for being so responsive!

2024-09-28 17:16 UTC, merged